name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Typescript
        run: yarn test --coverage

      - name: Build
        run: yarn prepare

      - name: Publish
        run: yarn publish
