name: CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --coverage

      - name: Typescript
        run: yarn typescript

      - name: Build
        run: yarn prepare

      - name: Version
        run: npm version ${GITHUB_REF/refs\/tags\//}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
